apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apex-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: apex
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apex
  source:
    repoURL: https://github.com/zhanserikAmangeldi/apex-be.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: apex-prod
  syncPolicy:
    # Prod requires manual sync for safety
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /status
