apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apex-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: apex
    environment: dev
spec:
  project: apex
  source:
    repoURL: https://github.com/zhanserikAmangeldi/apex-be.git
    targetRevision: develop
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: apex-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
